### PR TITLE
style: Make all methods start with lowercase letter

### PR DESCRIPTION
**Pull request by Kasijjuf**
except for the Switch() and Return() methods as both
their lowercase forms are reserved keywords

also changed the name of the "returner" class and
constructor to Returner

### CODE REVIEW

**Comment by Kasijjuf** [comment]
Merge conflict resolved.

**Comment by Tumbler** [comment]
I'll pull this when I get home.

Side note: Your comment suggests renaming Return() to result(). I'm not necessarily opposed to renaming it, but "result" doesn't make sense. You call Return() when you want to return to the previous menu that called you. I.E. main screen calls manage players menu. We're done editing players and click the save button. Now we call Return() to close the manage players menu and get back to the main screen.

**Comment by Kasijjuf** [comment]
OK. I wasn't clear on what that method did when I wrote that comment; result() was just the first valid name I thought of that was semantically similar.

**Comment by Kasijjuf** [comment]
Other method name ideas: finish(), exit(), done(), close()

**Pull request merged**
